### ISSUE TITLE
** (Code.LoadError) could not load /tmp/jason/priv/licenses.exs

### ISSUE THREAD

**Issue by kianmeng** [Cantido/hex_licenses#1]
Running on `asdf`:

```bash
$ asdf current
elixir          1.12.3-otp-24   /home/foobar/.tool-versions
erlang          24.0.5          /home/foobar/.tool-versions
```
Installed via `archived` method:

```bash
$ mix archive.install hex hex_licenses
```

Running the `mix licenses` against https://github.com/michalmuskala/jason.

```bash
$ cd /tmp
$ git clone https://github.com/michalmuskala/jason
$ cd jason
$ mix licenses
** (Code.LoadError) could not load /tmp/jason/priv/licenses.exs
    (elixir 1.12.3) lib/code.ex:1807: Code.find_file/2
    (elixir 1.12.3) lib/code.ex:1206: Code.eval_file/2
    lib/hex_licenses/spdx.ex:32: HexLicenses.SPDX.licenses/0
    lib/mix/tasks/licenses.ex:32: Mix.Tasks.Licenses.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

Did I miss out something?

**Comment by Cantido** [comment]
You didn't miss anything, I did. I'll get working on this, thank you!

**Comment by Cantido** [comment]
I just pushed version 0.3.1 to Hex, that should fix the issue for you :) thanks again for reporting this!
