### ISSUE TITLE
Deprecated licenses can't be explained

### ISSUE THREAD

**Issue by tcitworld** [Cantido/hex_licenses#3]
Another condition issue. 😇
```
ip_reserved has 1 unsafe licenses:
** (FunctionClauseError) no function clause matching in Mix.Tasks.Licenses.Explain.status_line/2    
    
    The following arguments were given to Mix.Tasks.Licenses.Explain.status_line/2:
    
        # 1
        "GPL-3.0+"
    
        # 2
        :deprecated
    
    Attempted function clauses (showing 2 out of 2):
    
        def status_line(license, :not_approved)
        def status_line(license, :not_recognized)
    
    lib/mix/tasks/licenses/explain.ex:74: Mix.Tasks.Licenses.Explain.status_line/2
    lib/mix/tasks/licenses/explain.ex:59: anonymous fn/1 in Mix.Tasks.Licenses.Explain.run/1
    (elixir 1.12.1) lib/enum.ex:935: anonymous fn/3 in Enum.each/2
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.1) lib/enum.ex:2368: Enum.each/2
    (elixir 1.12.1) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    lib/mix/tasks/licenses/explain.ex:52: Mix.Tasks.Licenses.Explain.run/1
    (mix 1.12.1) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
```

**Comment by Cantido** [comment]
Great catch, thank you so much! I forgot about that case in the printing section.

**Comment by Cantido** [comment]
Version v0.3.3 pushed, give it a try!

**Comment by tcitworld** [comment]
Perfect, thanks for the very quick fixes!
